'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bank_monthly_balances
    Public Property bm_Id As Integer
    Public Property bm_bank_Id As Integer
    Public Property bm_Month As Date
    Public Property bm_OpeningBalance As Integer
    Public Property bm_ClosingBalance As Integer
    Public Property bm_TotalDebit As Integer
    Public Property bm_TotalCredit As Integer

    Public Overridable Property bank As bank

End Class
