'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class car
    Public Property c_id As Integer
    Public Property c_cus_id As Nullable(Of Integer)
    Public Property c_no As String
    Public Property c_driver As String
    Public Property c_deposit_50 As Integer
    Public Property c_deposit_20 As Integer
    Public Property c_deposit_16 As Integer
    Public Property c_deposit_10 As Integer
    Public Property c_deposit_4 As Integer
    Public Property c_deposit_15 As Integer
    Public Property c_deposit_14 As Integer
    Public Property c_deposit_5 As Integer
    Public Property c_deposit_2 As Integer

    Public Overridable Property customer As customer
    Public Overridable Property orders As ICollection(Of order) = New HashSet(Of order)
    Public Overridable Property orders1 As ICollection(Of order) = New HashSet(Of order)

End Class
