'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cheque
    Public Property che_Id As Integer
    Public Property che_Date As Date
    Public Property che_Number As String
    Public Property che_Amount As Integer
    Public Property che_CashingDate As Nullable(Of Date)
    Public Property che_Memo As String
    Public Property che_IsCashing As Boolean
    Public Property che_Type As String

End Class
