'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class company
    Public Property comp_id As Integer
    Public Property comp_name As String
    Public Property comp_short As String
    Public Property comp_tax_id As String
    Public Property comp_memo As String
    Public Property comp_GasStock As Single

    Public Overridable Property collections As ICollection(Of collection) = New HashSet(Of collection)
    Public Overridable Property purchases As ICollection(Of purchase) = New HashSet(Of purchase)
    Public Overridable Property stocks As ICollection(Of stock) = New HashSet(Of stock)

End Class
