'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class employee
    Public Property emp_id As Integer
    Public Property emp_name As String
    Public Property emp_phone As String
    Public Property emp_address As String
    Public Property emp_ecp As String
    Public Property emp_ect As String
    Public Property emp_acc As String
    Public Property emp_psw As String
    Public Property emp_r_id As Nullable(Of Integer)
    Public Property emp_identity_number As String
    Public Property emp_birthday As Nullable(Of Date)

End Class
