'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class manufacturer
    Public Property manu_id As Integer
    Public Property manu_code As String
    Public Property manu_name As String
    Public Property manu_principal As String
    Public Property manu_contact_person As String
    Public Property manu_phone1 As String
    Public Property manu_phone2 As String
    Public Property manu_fax As String
    Public Property manu_address As String
    Public Property manu_bank As String
    Public Property manu_bank_code As String
    Public Property manu_branches As String
    Public Property manu_account As String
    Public Property manu_account_name As String
    Public Property manu_tax_id As String
    Public Property manu_memo As String
    Public Property manu_group As Nullable(Of Integer)
    Public Property manu_gas_normal As Nullable(Of Single)
    Public Property manu_gas_c As Nullable(Of Single)
    Public Property manu_GasVendor As Boolean

    Public Overridable Property payments As ICollection(Of payment) = New HashSet(Of payment)
    Public Overridable Property purchases As ICollection(Of purchase) = New HashSet(Of purchase)

End Class
