'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class order
    Public Property o_id As Integer
    Public Property o_date As Nullable(Of Date)
    Public Property o_c_id As Integer
    Public Property o_return As Integer
    Public Property o_return_c As Integer
    Public Property o_memo As String
    Public Property o_sales_allowance As Integer
    Public Property o_total_amount As Integer
    Public Property o_gas_50 As Integer
    Public Property o_gas_20 As Integer
    Public Property o_gas_16 As Integer
    Public Property o_gas_10 As Integer
    Public Property o_gas_4 As Integer
    Public Property o_gas_15 As Integer
    Public Property o_gas_14 As Integer
    Public Property o_gas_5 As Integer
    Public Property o_gas_2 As Integer
    Public Property o_gas_c_50 As Integer
    Public Property o_gas_c_20 As Integer
    Public Property o_gas_c_16 As Integer
    Public Property o_gas_c_10 As Integer
    Public Property o_gas_c_4 As Integer
    Public Property o_gas_c_15 As Integer
    Public Property o_gas_c_14 As Integer
    Public Property o_gas_c_5 As Integer
    Public Property o_gas_c_2 As Integer
    Public Property o_empty_50 As Integer
    Public Property o_empty_20 As Integer
    Public Property o_empty_16 As Integer
    Public Property o_empty_10 As Integer
    Public Property o_empty_4 As Integer
    Public Property o_empty_15 As Integer
    Public Property o_empty_14 As Integer
    Public Property o_empty_5 As Integer
    Public Property o_empty_2 As Integer
    Public Property o_deposit_out_50 As Integer
    Public Property o_deposit_out_20 As Integer
    Public Property o_deposit_out_16 As Integer
    Public Property o_deposit_out_10 As Integer
    Public Property o_deposit_out_4 As Integer
    Public Property o_deposit_out_15 As Integer
    Public Property o_deposit_out_14 As Integer
    Public Property o_deposit_out_5 As Integer
    Public Property o_deposit_out_2 As Integer
    Public Property o_deposit_out_c_id As Integer
    Public Property o_in_50 As Integer
    Public Property o_in_20 As Integer
    Public Property o_in_16 As Integer
    Public Property o_in_10 As Integer
    Public Property o_in_4 As Integer
    Public Property o_in_15 As Integer
    Public Property o_in_14 As Integer
    Public Property o_in_5 As Integer
    Public Property o_in_2 As Integer
    Public Property o_new_in_50 As Integer
    Public Property o_new_in_20 As Integer
    Public Property o_new_in_16 As Integer
    Public Property o_new_in_10 As Integer
    Public Property o_new_in_4 As Integer
    Public Property o_new_in_15 As Integer
    Public Property o_new_in_14 As Integer
    Public Property o_new_in_5 As Integer
    Public Property o_new_in_2 As Integer
    Public Property o_inspect_50 As Integer
    Public Property o_inspect_20 As Integer
    Public Property o_inspect_16 As Integer
    Public Property o_inspect_10 As Integer
    Public Property o_inspect_4 As Integer
    Public Property o_inspect_15 As Integer
    Public Property o_inspect_14 As Integer
    Public Property o_inspect_5 As Integer
    Public Property o_inspect_2 As Integer
    Public Property o_deposit_in_50 As Integer
    Public Property o_deposit_in_20 As Integer
    Public Property o_deposit_in_16 As Integer
    Public Property o_deposit_in_10 As Integer
    Public Property o_deposit_in_4 As Integer
    Public Property o_deposit_in_15 As Integer
    Public Property o_deposit_in_14 As Integer
    Public Property o_deposit_in_5 As Integer
    Public Property o_deposit_in_2 As Integer
    Public Property o_delivery_type As String
    Public Property o_in_out As String

    Public Overridable Property car As car
    Public Overridable Property car1 As car

End Class
