'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class purchase
    Public Property pur_id As Integer
    Public Property pur_manu_id As Integer
    Public Property pur_date As Nullable(Of Date)
    Public Property pur_product As String
    Public Property pur_quantity As Nullable(Of Integer)
    Public Property pur_unit_price As Nullable(Of Single)
    Public Property pur_price As Nullable(Of Single)
    Public Property pur_comp_id As Integer
    Public Property pur_deli_unit_price As Nullable(Of Single)
    Public Property pur_delivery_fee As Nullable(Of Single)
    Public Property pur_Special As Boolean

    Public Overridable Property manufacturer As manufacturer
    Public Overridable Property company As company

End Class
