'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class subject
    Public Property s_id As Integer
    Public Property s_Type As String
    Public Property s_name As String
    Public Property s_memo As String

    Public Overridable Property collections As ICollection(Of collection) = New HashSet(Of collection)
    Public Overridable Property journals As ICollection(Of journal) = New HashSet(Of journal)
    Public Overridable Property payments As ICollection(Of payment) = New HashSet(Of payment)

End Class
