'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class subjects_group
    Public Property sg_id As Integer
    Public Property sg_name As String
    Public Property sg_type As String

    Public Overridable Property subjects As ICollection(Of subject) = New HashSet(Of subject)

End Class
