'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class accounting_entry
    Public Property ae_Id As Integer
    Public Property ae_TransactionType As String
    Public Property ae_TransactionId As Integer
    Public Property ae_Date As Date
    Public Property ae_s_Id As Integer
    Public Property ae_Debit As Nullable(Of Double)
    Public Property ae_Credit As Nullable(Of Double)

End Class
