'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class barrel_monthly_balances
    Public Property barmb_Id As Integer
    Public Property barmb_gb_Id As Integer
    Public Property barmb_Month As Date
    Public Property barmb_OpeningBalance As Integer
    Public Property barmb_ClosingBalance As Integer
    Public Property barmb_Total As Integer

    Public Overridable Property gas_barrel As gas_barrel

End Class
