'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class chque_pay
    Public Property cp_Id As Integer
    Public Property cp_Date As Nullable(Of Date)
    Public Property cp_Number As String
    Public Property cp_Amount As Nullable(Of Integer)
    Public Property cp_CashingDate As Nullable(Of Date)
    Public Property cp_Memo As String
    Public Property cp_IsCashing As Nullable(Of Boolean)
    Public Property cp_BankCashing As Nullable(Of Date)

    Public Overridable Property payments As ICollection(Of payment) = New HashSet(Of payment)

End Class
