'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class closing_entry
    Public Property ce_Id As Integer
    Public Property ce_Date As Nullable(Of Date)
    Public Property ce_Debit As Nullable(Of Integer)
    Public Property ce_DebitMemo As String
    Public Property ce_DebitAmount As Nullable(Of Double)
    Public Property ce_Credit As Nullable(Of Integer)
    Public Property ce_CreditMemo As String
    Public Property ce_CreditAmount As Nullable(Of Double)

    Public Overridable Property subject As subject
    Public Overridable Property subject1 As subject

End Class
