'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class collection
    Public Property col_Id As Integer
    Public Property col_Date As Date
    Public Property col_AccountMonth As Date
    Public Property col_Amount As Integer
    Public Property col_Type As String
    Public Property col_Cheque As String
    Public Property col_cus_Id As Nullable(Of Integer)
    Public Property col_s_Id As Nullable(Of Integer)
    Public Property col_Memo As String
    Public Property col_bank_Id As Nullable(Of Integer)
    Public Property col_comp_Id As Nullable(Of Integer)
    Public Property col_UnmatchedAmount As Integer
    Public Property col_credit_bank_id As Nullable(Of Integer)
    Public Property col_credit_company_id As Nullable(Of Integer)
    Public Property col_s_Id_2 As Nullable(Of Integer)
    Public Property col_credit_bank_id_2 As Nullable(Of Integer)
    Public Property col_credit_company_id_2 As Nullable(Of Integer)
    Public Property col_s_Id_3 As Nullable(Of Integer)
    Public Property col_credit_bank_id_3 As Nullable(Of Integer)
    Public Property col_credit_company_id_3 As Nullable(Of Integer)
    Public Property col_credit_amount_1 As Nullable(Of Integer)
    Public Property col_credit_amount_2 As Nullable(Of Integer)
    Public Property col_credit_amount_3 As Nullable(Of Integer)
    Public Property col_AccountMonth2 As Nullable(Of Date)
    Public Property col_AccountMonth3 As Nullable(Of Date)

    Public Overridable Property bank As bank
    Public Overridable Property bank1 As bank
    Public Overridable Property bank2 As bank
    Public Overridable Property bank3 As bank
    Public Overridable Property cheques As ICollection(Of cheque) = New HashSet(Of cheque)
    Public Overridable Property customer As customer
    Public Overridable Property subject As subject
    Public Overridable Property company As company
    Public Overridable Property subject1 As subject
    Public Overridable Property company1 As company
    Public Overridable Property company2 As company
    Public Overridable Property subject2 As subject
    Public Overridable Property company3 As company
    Public Overridable Property order_collection_mapping As ICollection(Of order_collection_mapping) = New HashSet(Of order_collection_mapping)
    Public Overridable Property write_off As ICollection(Of write_off) = New HashSet(Of write_off)

End Class
