'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class collection_detail
    Public Property cd_Id As Integer
    Public Property cd_col_Id As Integer
    Public Property cd_s_Id As Nullable(Of Integer)
    Public Property cd_bank_Id As Nullable(Of Integer)
    Public Property cd_Amount As Integer
    Public Property cd_Memo As String
    Public Property cd_che_Id As Nullable(Of Integer)

    Public Overridable Property bank As bank
    Public Overridable Property cheque As cheque
    Public Overridable Property collection As collection
    Public Overridable Property subject As subject

End Class
