'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class customer
    Public Property cus_id As Integer
    Public Property cus_code As String
    Public Property cus_name As String
    Public Property cus_principal As String
    Public Property cus_contact_person As String
    Public Property cus_phone1 As String
    Public Property cus_phone2 As String
    Public Property cus_fax As String
    Public Property cus_address As String
    Public Property cus_tax_id As String
    Public Property cus_memo As String
    Public Property cus_gas_50 As Integer
    Public Property cus_gas_20 As Integer
    Public Property cus_gas_16 As Integer
    Public Property cus_gas_10 As Integer
    Public Property cus_gas_4 As Integer
    Public Property cus_gas_18 As Integer
    Public Property cus_gas_14 As Integer
    Public Property cus_gas_5 As Integer
    Public Property cus_gas_2 As Integer
    Public Property cus_pp_Id As Nullable(Of Integer)
    Public Property cus_inspect_50 As Integer
    Public Property cus_inspect_20 As Integer
    Public Property cus_inspect_16 As Integer
    Public Property cus_inspect_10 As Integer
    Public Property cus_inspect_4 As Integer
    Public Property cus_inspect_18 As Integer
    Public Property cus_inspect_14 As Integer
    Public Property cus_inspect_5 As Integer
    Public Property cus_inspect_2 As Integer
    Public Property cus_IsInsurance As Boolean
    Public Property cus_InsurancePrice As Single
    Public Property cus_comp_Id As Nullable(Of Integer)
    Public Property cus_InvoiceMemo As String

    Public Overridable Property cars As ICollection(Of car) = New HashSet(Of car)
    Public Overridable Property cars1 As ICollection(Of car) = New HashSet(Of car)
    Public Overridable Property collections As ICollection(Of collection) = New HashSet(Of collection)
    Public Overridable Property company As company
    Public Overridable Property priceplan As priceplan
    Public Overridable Property inspections As ICollection(Of inspection) = New HashSet(Of inspection)
    Public Overridable Property invoices As ICollection(Of invoice) = New HashSet(Of invoice)
    Public Overridable Property monthly_account As ICollection(Of monthly_account) = New HashSet(Of monthly_account)
    Public Overridable Property orders As ICollection(Of order) = New HashSet(Of order)
    Public Overridable Property scrap_barrel_detail As ICollection(Of scrap_barrel_detail) = New HashSet(Of scrap_barrel_detail)

End Class
