'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class gas_monthly_balances
    Public Property gmb_Id As Integer
    Public Property gmb_Month As Date
    Public Property gmb_comp_Id As Integer
    Public Property gmb_OpeningBalance As Integer
    Public Property gmb_PurchaseTotal As Integer
    Public Property gmb_SaleTotal As Integer
    Public Property gmb_ClosingBalance As Integer

    Public Overridable Property company As company

End Class
