'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class gas_barrel
    Public Property gb_Id As Integer
    Public Property gb_Name As String
    Public Property gb_InitialInventory As Integer
    Public Property gb_Inventory As Integer
    Public Property gb_SalesPrice As Integer

    Public Overridable Property barrel_monthly_balances As ICollection(Of barrel_monthly_balances) = New HashSet(Of barrel_monthly_balances)

End Class
