'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class inspection
    Public Property in_Id As Integer
    Public Property in_Month As Nullable(Of Date)
    Public Property in_cus_Id As Nullable(Of Integer)
    Public Property in_Qty50 As Nullable(Of Integer)
    Public Property in_Price50 As Nullable(Of Double)
    Public Property in_Amount50 As Nullable(Of Double)
    Public Property in_Qty20 As Nullable(Of Integer)
    Public Property in_Price20 As Nullable(Of Double)
    Public Property in_Amount20 As Nullable(Of Double)
    Public Property in_Qty16 As Nullable(Of Integer)
    Public Property in_Price16 As Nullable(Of Double)
    Public Property in_Amount16 As Nullable(Of Double)
    Public Property in_Qty10 As Nullable(Of Integer)
    Public Property in_Price10 As Nullable(Of Double)
    Public Property in_Amount10 As Nullable(Of Double)
    Public Property in_Qty4 As Nullable(Of Integer)
    Public Property in_Price4 As Nullable(Of Double)
    Public Property in_Amount4 As Nullable(Of Double)
    Public Property in_QtySwitch As Nullable(Of Integer)
    Public Property in_PriceSwitch As Nullable(Of Double)
    Public Property in_AmountSwitch As Nullable(Of Double)
    Public Property in_QtyFreight As Nullable(Of Integer)
    Public Property in_PriceFreight As Nullable(Of Double)
    Public Property in_AmountFreight As Nullable(Of Double)
    Public Property in_QtyRustProof As Nullable(Of Integer)
    Public Property in_PriceRustProof As Nullable(Of Double)
    Public Property in_AmountRustProof As Nullable(Of Double)
    Public Property in_QtySpraying As Nullable(Of Integer)
    Public Property in_PriceSpraying As Nullable(Of Integer)
    Public Property in_AmountSpraying As Nullable(Of Integer)
    Public Property in_QtyTotal As Nullable(Of Integer)
    Public Property in_PriceTotal As Nullable(Of Double)
    Public Property in_AmountTotal As Nullable(Of Double)

    Public Overridable Property customer As customer

End Class
