'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class invoice
    Public Property i_Id As Integer
    Public Property i_cus_Id As Integer
    Public Property i_Number As String
    Public Property i_Amount As Single
    Public Property i_Date As Date
    Public Property i_KG As Integer
    Public Property i_UnitPrice As Single
    Public Property i_Tax As Single
    Public Property i_Type As String
    Public Property i_Memo As String

    Public Overridable Property customer As customer

End Class
