'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class invoice_split
    Public Property is_Id As Integer
    Public Property is_Date As Date
    Public Property is_Name As String
    Public Property is_Tax As Single
    Public Property is_Amount As Single
    Public Property is_VendorTaxId As String
    Public Property is_Number As String
    Public Property is_Type As String
    Public Property is_comp_Id As Nullable(Of Integer)

    Public Overridable Property company As company

End Class
