'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class gas_accounting_systemEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=gas_accounting_systemEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property accounting_entry() As DbSet(Of accounting_entry)
    Public Overridable Property banks() As DbSet(Of bank)
    Public Overridable Property bank_monthly_balances() As DbSet(Of bank_monthly_balances)
    Public Overridable Property barrel_monthly_balances() As DbSet(Of barrel_monthly_balances)
    Public Overridable Property basic_price() As DbSet(Of basic_price)
    Public Overridable Property basic_set() As DbSet(Of basic_set)
    Public Overridable Property cars() As DbSet(Of car)
    Public Overridable Property cheques() As DbSet(Of cheque)
    Public Overridable Property chque_pay() As DbSet(Of chque_pay)
    Public Overridable Property closing_entry() As DbSet(Of closing_entry)
    Public Overridable Property collections() As DbSet(Of collection)
    Public Overridable Property companies() As DbSet(Of company)
    Public Overridable Property customers() As DbSet(Of customer)
    Public Overridable Property employees() As DbSet(Of employee)
    Public Overridable Property gas_barrel() As DbSet(Of gas_barrel)
    Public Overridable Property gas_monthly_balances() As DbSet(Of gas_monthly_balances)
    Public Overridable Property inspections() As DbSet(Of inspection)
    Public Overridable Property invoices() As DbSet(Of invoice)
    Public Overridable Property invoice_split() As DbSet(Of invoice_split)
    Public Overridable Property manufacturers() As DbSet(Of manufacturer)
    Public Overridable Property monthly_account() As DbSet(Of monthly_account)
    Public Overridable Property order_collection_mapping() As DbSet(Of order_collection_mapping)
    Public Overridable Property orders() As DbSet(Of order)
    Public Overridable Property payments() As DbSet(Of payment)
    Public Overridable Property permissions() As DbSet(Of permission)
    Public Overridable Property priceplans() As DbSet(Of priceplan)
    Public Overridable Property purchase_barrel() As DbSet(Of purchase_barrel)
    Public Overridable Property rolepermissions() As DbSet(Of rolepermission)
    Public Overridable Property roles() As DbSet(Of role)
    Public Overridable Property scrap_barrel() As DbSet(Of scrap_barrel)
    Public Overridable Property scrap_barrel_detail() As DbSet(Of scrap_barrel_detail)
    Public Overridable Property stocks() As DbSet(Of stock)
    Public Overridable Property subjects() As DbSet(Of subject)
    Public Overridable Property surplus_gas() As DbSet(Of surplus_gas)
    Public Overridable Property write_off() As DbSet(Of write_off)
    Public Overridable Property purchases() As DbSet(Of purchase)

End Class
