'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class monthly_account
    Public Property ma_id As Integer
    Public Property ma_cus_id As Integer
    Public Property ma_year As Integer
    Public Property ma_month As Integer
    Public Property ma_total_amount As Integer
    Public Property ma_paid_amount As Integer
    Public Property ma_unpaid_amount As Integer
    Public Property ma_status As Boolean
    Public Property ma_last_updated As Date
    Public Property ma_discount As Nullable(Of Integer)

    Public Overridable Property customer As customer
    Public Overridable Property write_off As ICollection(Of write_off) = New HashSet(Of write_off)

End Class
