'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class order_collection_mapping
    Public Property ocm_Id As Integer
    Public Property ocm_o_Id As Integer
    Public Property ocm_col_Id As Integer
    Public Property ocm_Amount As Integer
    Public Property ocm_Date As Date

    Public Overridable Property collection As collection
    Public Overridable Property order As order

End Class
