'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class payment_cheque
    Public Property pc_id As Integer
    Public Property pc_p_id As Integer
    Public Property pc_cp_id As Integer

    Public Overridable Property chque_pay As chque_pay
    Public Overridable Property payment As payment

End Class
