'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class permission
    Public Property per_Id As Integer
    Public Property per_TabPageName As String
    Public Property per_Name As String

    Public Overridable Property rolepermissions As ICollection(Of rolepermission) = New HashSet(Of rolepermission)
    Public Overridable Property rolepermissions1 As ICollection(Of rolepermission) = New HashSet(Of rolepermission)

End Class
