'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class priceplan
    Public Property pp_Id As Integer
    Public Property pp_Name As String
    Public Property pp_Gas As Single
    Public Property pp_Gas_c As Single
    Public Property pp_GasDelivery As Single
    Public Property pp_GasDelivery_c As Single

    Public Overridable Property customers As ICollection(Of customer) = New HashSet(Of customer)

End Class
