'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class purchase_barrel
    Public Property pb_Id As Integer
    Public Property pb_manu_Id As Integer
    Public Property pb_Qty_50 As Nullable(Of Integer)
    Public Property pb_UnitPrice_50 As Nullable(Of Integer)
    Public Property pb_Qty_20 As Nullable(Of Integer)
    Public Property pb_UnitPrice_20 As Nullable(Of Integer)
    Public Property pb_Qty_16 As Nullable(Of Integer)
    Public Property pb_UnitPrice_16 As Nullable(Of Integer)
    Public Property pb_Qty_10 As Nullable(Of Integer)
    Public Property pb_UnitPrice_10 As Nullable(Of Integer)
    Public Property pb_Qty_4 As Nullable(Of Integer)
    Public Property pb_UnitPrice_4 As Nullable(Of Integer)
    Public Property pb_Qty_18 As Nullable(Of Integer)
    Public Property pb_UnitPrice_18 As Nullable(Of Integer)
    Public Property pb_Qty_14 As Nullable(Of Integer)
    Public Property pb_UnitPrice_14 As Nullable(Of Integer)
    Public Property pb_Qty_5 As Nullable(Of Integer)
    Public Property pb_UnitPrice_5 As Nullable(Of Integer)
    Public Property pb_Qty_2 As Nullable(Of Integer)
    Public Property pb_UnitPrice_2 As Nullable(Of Integer)
    Public Property pb_Amount As Integer
    Public Property pb_Date As Date
    Public Property pb_comp_Id As Nullable(Of Integer)

    Public Overridable Property manufacturer As manufacturer
    Public Overridable Property company As company
    Public Overridable Property company1 As company

End Class
