'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class scrap_barrel
    Public Property sb_Id As Integer
    Public Property sb_Month As Nullable(Of Date)
    Public Property sb_Acquisitions50 As Nullable(Of Integer)
    Public Property sb_Buy50 As Nullable(Of Integer)
    Public Property sb_Acquisitions20 As Nullable(Of Integer)
    Public Property sb_Buy20 As Nullable(Of Integer)
    Public Property sb_Acquisitions16 As Nullable(Of Integer)
    Public Property sb_Buy16 As Nullable(Of Integer)
    Public Property sb_Acquisitions10 As Nullable(Of Integer)
    Public Property sb_Buy10 As Nullable(Of Integer)
    Public Property sb_Acquisitions4 As Nullable(Of Integer)
    Public Property sb_Buy4 As Nullable(Of Integer)

    Public Overridable Property scrap_barrel_detail As ICollection(Of scrap_barrel_detail) = New HashSet(Of scrap_barrel_detail)

End Class
