'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class scrap_barrel_detail
    Public Property sbd_Id As Integer
    Public Property sbd_cus_Id As Nullable(Of Integer)
    Public Property sbd_Qty50 As Nullable(Of Integer)
    Public Property sbd_Qty20 As Nullable(Of Integer)
    Public Property sbd_Qty16 As Nullable(Of Integer)
    Public Property sbd_Qty10 As Nullable(Of Integer)
    Public Property sbd_Qty4 As Nullable(Of Integer)
    Public Property sbd_sb_Id As Nullable(Of Integer)

    Public Overridable Property customer As customer
    Public Overridable Property scrap_barrel As scrap_barrel

End Class
