'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class surplus_gas
    Public Property sg_Id As Integer
    Public Property sg_StartDate As Nullable(Of Date)
    Public Property sg_EndDate As Nullable(Of Date)
    Public Property sg_Moth As Nullable(Of Date)
    Public Property sg_Platform As Nullable(Of Integer)
    Public Property sg_Platform_C As Nullable(Of Integer)
    Public Property sg_Slot As Nullable(Of Integer)
    Public Property sg_Slot_C As Nullable(Of Integer)
    Public Property sg_Car As Nullable(Of Integer)
    Public Property sg_Car_C As Nullable(Of Integer)
    Public Property sg_Sell As Nullable(Of Integer)
    Public Property sg_Total As Nullable(Of Integer)

End Class
