'------------------------------------------------------------------------------
' <auto-generated>
'     這個程式碼是由範本產生。
'
'     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
'     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class write_off
    Public Property wo_id As Integer
    Public Property wo_col_id As Integer
    Public Property wo_amount As Integer
    Public Property wo_date As Date
    Public Property wo_ma_id As Integer

    Public Overridable Property monthly_account As monthly_account
    Public Overridable Property collection As collection

End Class
